name: Build Android OTP Forwarder APK

  on:
    push:
      branches: [ main, master ]
    pull_request:
      branches: [ main, master ]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Clean project
        run: ./gradlew clean

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-otp-forwarder-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Create Release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Android OTP Forwarder v${{ github.run_number }}
          body: |
            ## Android OTP Forwarder - Enhanced Version

            ### New Features:
            - Persistent Background Service (never gets killed)
            - Offline Message Queuing (saves OTPs when no internet)
            - Auto-Retry when connection restored
            - Smart Subscription Validation
            - Android 5-14 Compatibility
            - Battery Optimization Exemption

            ### Installation:
            1. Download app-release.apk
            2. Enable "Install from unknown sources"
            3. Install the APK
            4. Grant all permissions
            5. Configure your settings
            6. Service starts automatically!

            Built with GitHub Actions - Professional build environment.
          files: app/build/outputs/apk/release/app-release.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
