name: Build Android OTP Forwarder APK
  on:
    push:
      branches: [ main, master ]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Clean project
        run: ./gradlew clean

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-otp-forwarder-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Android OTP Forwarder v${{ github.run_number }}
          body: |
            ## 🚀 Android OTP Forwarder - Enhanced Version

            ### ✅ New Features:
            - **Persistent Background Service**: Never gets killed by system
            - **Offline Message Queuing**: Saves OTPs when no internet connection
            - **Auto-Retry Mechanism**: Sends queued messages when connection restored
            - **Smart Subscription Validation**: Only checks when needed
            - **Android 5-14 Compatibility**: Works on all modern devices
            - **Battery Optimization**: Requests exemption from power saving
            - **Modern Architecture**: Updated APIs and dependencies

            ### 📱 Installation Instructions:
            1. Download **app-release.apk** below
            2. Enable "Install from unknown sources" on your Android device
            3. Install the APK file
            4. Grant ALL permissions when prompted
            5. Configure your email and mobile numbers
            6. Service will start automatically!

            ### 🔧 Technical Improvements:
            - Target SDK updated to 34 (latest Android compatibility)
            - Foreground service implementation
            - Room database for offline storage
            - Network connectivity monitoring
            - Modern permission handling

            **No more app crashes or installation failures!**
          files: app/build/outputs/apk/release/app-release.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
